config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :projects do 
    resources :comments, only: [:create]
    resources :status_histories, only: [:create]
  end
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project


  def user_name
    user.name
  end 

  def pretty_date
    created_at.strftime("%b %e, %l:%M %p")
  end 
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :status_histories, dependent: :destroy
end

app/models/status_history.rb
class StatusHistory < ApplicationRecord
  belongs_to :user
  belongs_to :project


  def pretty_date
    created_at.strftime("%b %e, %l:%M %p")
  end 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :comments
  has_many :status_histories

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    puts "projects = #{@projects}"
  end 

  def show
    @project = Project.find(params[:id])
    @comments = @project.comments.order(:created_at)
    @status_histories = @project.status_histories.order(:created_at)
    @history = (@comments + @status_histories).sort_by(&:created_at)
  end 

end 

app/controllers/status_histories_controller.rb
class StatusHistoriesController < ApplicationController

  def create
    @project = Project.find(params[:project_id])

    @status_history = @project.status_histories.build(status_history_params)
    @status_history.user = User.first 

    if @status_history.save
      @project.update(status: @status_history.new_status)
      redirect_to @project, notice: "Gains being made!"
    else
      redirect_to @project, alert: "Your gains failed"
    end
  end 

  private

  def status_history_params
    params.require(:status_history).permit(:previous_status, :new_status)
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= content_for(:title) || "Convo History" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/projects/index.html.erb
<div class='container'>
  <h1> Health Projects </h1>
  <div id="projects">
    <% @projects.each do |project| %>

    <div class="project-info">
      <%= link_to project.name, project_path(project) %>
    </div>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
  <h1><%= @project.name %></h1>
  
  <% if @project.status == "open" %>
    <%= render "shared/status_button", project: @project, label: "Close Project", prev_status: "open", new_status: "closed" %>
  <% else %>
    <%= render "shared/status_button", project: @project, label: "Reopen Project", prev_status: "closed", new_status: "open" %>
  <% end %>


  <div class='history'>
    <% @history.each do |item| %>
      <% if item.is_a?(Comment) %>
        <div class="history-item">
          <p><%= item.body %></p>
          <div>
            <%= item.user.name %> at
            <%= item.pretty_date %>
          </div>
        </div>

      <% else %>
          <div class="history-item">
            <%= item.user.name %> changed status from <%= item.previous_status %> to <%= item.new_status %> on 
            <%= item.pretty_date %>
          </div>
      <% end %>
    <% end %>
  </div>

  <% if @project.status === "open" %>
    <%=  form_with model: [@project, Comment.new] do |form| %>
      <div>
        <%= form.text_area :body, placeholder: 'add new comment' %>
        <%= form.submit "Post" %>
      </div>
    <% end %>
  <% else %>
    <div>No gains here the project is closed! Swole you later</div>
  <% end %>
</div>

app/views/shared/_status_button.html.erb
<%= button_to label,
  project_status_histories_path(project),
  method: :post,
  params: {
    status_history: {
      previous_status: prev_status,
      new_status: new_status
    }
  },
  class: "button" 
%>